テストルート修正

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,16 +1,16 @@
 name: Rails CI # ワークフローの名前
 on:
   push:
-  # TODO一旦コメントアウト
-  # branches: [main] # mainブランチにpushされた時に実行
+    # TODO一旦コメントアウト
+    branches: [main] # mainブランチにpushされた時に実行
   pull_request:
-    # branches: [main] # mainブランチへのプルリクエスト時に実行
+    branches: [main] # mainブランチへのプルリクエスト時に実行
 
 jobs:
   test: # ジョブ名
     runs-on: ubuntu-latest
 
-    services:
+    services: # ジョブ開始時にbgで動作し続ける、stepsはその後に順次実行
       mysql: #
         image: mysql:8.0
         env:
@@ -63,8 +63,8 @@ jobs:
           echo "最初のテストを実行..."
           # まず1つのテストファイルだけ実行
           if [ -d spec ]; then  # RSpecディレクトリがある場合
-            bundle exec rspec spec/models/ --fail-fast || echo "テスト失敗（続行）"  # モデルテストのみ実行し、--fail-fast オプションは最初の失敗でテストを止める
+            bundle exec rspec --fail-fast || echo "テスト失敗（続行）"  # spce/フォルダ以下全てのテスト実行 --fail-fast オプションは最初の失敗でテストを止める
           else  # specがない場合はMinitestを想定
             echo "specディレクトリが見つかりません"
-            bundle exec rails test test/models/ || echo "テスト失敗（続行）"
+            bundle exec rails test || echo "テスト失敗（続行）"
           fi
